
modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/example/ema/issues"

[[mods]]
modId="ema"
version="1.0.0"
displayName="Extreme Molecular Assembler"
authors="Jules"
description='''
An addon for Applied Energistics 2 that adds an Extreme Molecular Assembler for larger crafting recipes.
'''

[[dependencies.ema]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ema]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ema]]
    modId="ae2"
    mandatory=true
    versionRange="[15.4.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ema]]
    modId="extendedcrafting"
    mandatory=true
    versionRange="[6.0.10,)"
    ordering="NONE"
    side="BOTH"
